# Generated by Django 4.0.1 on 2022-02-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_message_alter_room_host_delete_user_message_room_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
